### ISSUE TITLE
Plan of the fivetran_log_connector always produces a diff

### ISSUE THREAD

**Issue by michael-robbins** [fivetran/terraform-provider-fivetran#86] opened 2023-01-24 06:50 UTC
When attempting to run a terraform plan for the fivetran_log_connector it always seems to produce a plan:
```
  # module.fivetran_log_connector.fivetran_connector.fivetran_log will be updated in-place
  ~ resource "fivetran_connector" "fivetran_log" {
        id                = "my_id_goes_here"
        name              = "fivetran_log"
        # (13 unchanged attributes hidden)

      ~ config {
          + abs_connection_string                = ""
          + abs_container_name                   = ""
          + access_key_id                        = ""
          + access_token                         = (sensitive value)
          + account                              = ""
          + account_id                           = ""

..... lots of options....

          + user_name                            = ""
          + username                             = ""
          + view_attribution_window              = ""
          + view_through_attribution_window_size = ""
            # (30 unchanged attributes hidden)

          + project_credentials {
              + api_key    = (sensitive value)
              + project    = "fivetran_log"
              + secret_key = (sensitive value)
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

And when we continually apply the plan it keeps showing these again and again. Is there any way to avoid this?

**Comment by michael-robbins** [comment] 2023-01-24 06:52
When running with `TF_LOG=debug` I see the following as well:
```
module.fivetran_log_connector.fivetran_connector.fivetran_log: Refreshing state... [id=my_id_goes_here]
2023-01-24T17:42:46.214+1100 [WARN]  Provider "registry.terraform.io/fivetran/fivetran" produced an unexpected new value for module.fivetran_log_connector.fivetran_connector.fivetran_log during refresh.
      - .config[0].skip_before: was cty.StringVal("0"), but now cty.StringVal("")
      - .config[0].is_account_level_connector: was null, but now cty.StringVal("false")
      - .config[0].skip_after: was cty.StringVal("0"), but now cty.StringVal("")
      - .config[0].sync_method: was null, but now cty.StringVal("")
      - .config[0].share_url: was null, but now cty.StringVal("")
      - .config[0].is_keypair: was null, but now cty.StringVal("")
2023-01-24T17:42:46.228+1100 [WARN]  Provider "registry.terraform.io/fivetran/fivetran" produced an invalid plan for module.fivetran_log_connector.fivetran_connector.fivetran_log, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .config[0].consumer_secret: sensitive planned value for a non-computed attribute
      - .config[0].message_type: planned value cty.StringVal("") for a non-computed attribute
      - .config[0].network_code: planned value cty.StringVal("") for a non-computed attribute
      - .config[0].security_protocol: planned value cty.StringVal("") for a non-computed attribute
      - .config[0].share_url: planned value cty.StringVal("") for a non-computed attribute
      - .config[0].shop: planned value cty.StringVal("") for a non-computed attribute
      - .config[0].abs_container_name: planned value cty.StringVal("") for a non-computed attribute
      - .config[0].finance_accounts: planned value cty.ListValEmpty(cty.String) for a non-computed attribute

... lots of these ...

      - .config[0].publication_name: planned value cty.StringVal("") for a non-computed attribute
      - .config[0].repositories: planned value cty.ListValEmpty(cty.String) for a non-computed attribute
      - .config[0].role: planned value cty.StringVal("") for a non-computed attribute
      - .config[0].unique_id: planned value cty.StringVal("") for a non-computed attribute
      - .destination_schema[0].prefix: planned value cty.StringVal("") for a non-computed attribute
      - .destination_schema[0].table: planned value cty.StringVal("") for a non-computed attribute
```

**Comment by beevital** [comment] 2023-01-25 13:05
Hey @michael-robbins !

What version you are on? 
Could you please provide an example of your configuration?

We had such issue with drifting changes, but it had been fixed.

**Comment by beevital** [comment] 2023-07-12 14:06
@michael-robbins I'm unable to reproduce the issue on v0.6.19 and latest v0.7.2-pre 
There's no updates here since Jan 25. Closing the issue.

**Closed by beevital** 2023-07-12 14:06 UTC
