### ISSUE TITLE
fivetran_webhook triggers update when there are no changes and creates an error

### ISSUE THREAD

**Issue by adrian-montero-hkkd** [fivetran/terraform-provider-fivetran#262] opened 2024-02-15 16:37 UTC
This is a follow up on an issue opened before: https://github.com/fivetran/terraform-provider-fivetran/issues/239

**Describe the bug**
I had over 200+ webhooks setup and did no change to them and now all the webhooks show as "update" in plan although I did not change anything on them. So in the plan I get all the webhooks with this change:
![image](https://github.com/fivetran/terraform-provider-fivetran/assets/145811752/c88cd3e5-a432-43e8-a8c4-21db90068b8b)
And later get this result in the apply:
![image](https://github.com/fivetran/terraform-provider-fivetran/assets/145811752/2d3a3c80-ce1b-473b-9894-265a172c7832)
After I apply the plan and re-run a plan-apply cycle with no changes I get yet again this in the plan:
![image](https://github.com/fivetran/terraform-provider-fivetran/assets/145811752/5403c9a5-828a-4b03-9ec5-f966df601bbf)
Just like if in the previous cycle that attribute was not changed in the webhook.

**To Reproduce**
Create a webhook with the active property set to true and run plan/apply cycle twice, the error will show up on all cycles besides the first one.
```
resource "fivetran_webhook" "tf_webhook_prod" {
  type = "group"
  group_id = fivetran_group.fivetran_group.id
  url = "https://myurl.site.com"
  active = true
  events = [
    "sync_start",
    "sync_end",
    "create_connector",
    "pause_connector",
    "resume_connector",
    "delete_connector",
    "connection_successful",
    "connection_failure"
    ]
  secret = "<redacted>"
}
```

**Expected behavior**
Create the webhook the first time and DO NOT trigger update when conditions in the definition do not change.

**Plugin version:**
1.1.13

**Comment by beevital** [comment] 2024-03-11 16:17
Hey @adrian-montero-hkkd! 
I suspect that your webhooks were deactivated due to some reason: for example Fivetran wasn't able to deliver events. We de-activate webhooks that we can't deliver for a long period: [please, read more about it here.](https://fivetran.com/docs/rest-api/webhooks#automaticdeactivation).

On activation we always checking if the url is active and ready to respond. If we can't deliver test event on activation we return: 
`status code: 400; expected: 200; code: InvalidInput; message: Failed to call webhook endpoint:`

On your screenshot I can't see message part, it looks like error message is trimmed or clipped. But I suspect the problem is that your url doesn't respond with 2xx - that's why you can't re-activate your webhooks.

If you'll share your `group_id` we can make an investigation and find out exact  reason why and when your webhooks were de-activated.

There's no terraform problem here - provider works exactly as expected, so I have to close this issue.

**Closed by beevital** 2024-03-11 16:17 UTC
Labels: bug
