### ISSUE TITLE
Connector creating fails half-way through when schema config is defined on azure_sql_db service

### ISSUE THREAD

**Issue by puchtawxebia** [fivetran/terraform-provider-fivetran#183] opened 2023-08-04 09:13 UTC
**Describe the bug**
When applying `fivetran_connector` with `fivetran_connector_schedule` and `fivetran_connector_schema_config` I get the error message. In the GUI connector has status INCOMPLETE and has to be manually fixed by clicking "Save & test". However, without `fivetran_connector_schema_config` the connector seems to be created all right.

**To Reproduce**
```terraform
resource "fivetran_connector" "this" {
  group_id           = fivetran_destination.this.group_id
  service            = "azure_sql_db"
  trust_certificates = true
  trust_fingerprints = true
  run_setup_tests    = true

  destination_schema {
    prefix = lower(var.tenant_id)
  }

  config {
    database      = local.source_db_name
    host          = local.source_db_host
    port          = 1433
    user          = local.source_db_user
    password      = local.source_db_password
    update_method = var.connector.update_method
  }
  depends_on = [fivetran_destination.this]
}

resource "fivetran_connector_schedule" "this" {
  connector_id = fivetran_connector.this.id

  paused            = false
  pause_after_trial = false
  sync_frequency    = 1440
  schedule_type     = "auto"

  depends_on = [
    fivetran_connector.this
  ]
}

resource "fivetran_connector_schema_config" "this" {
  connector_id           = fivetran_connector.this.id
  schema_change_handling = var.connector_schema.change_handling
  dynamic "schema" {
    for_each = var.connector_schema.schemas
    content {
      name = schema.key
      dynamic "table" {
        for_each = toset(schema.value)
        content {
          name = table.value
        }
      }
    }
  }
  # removing depends_on blocks will not fix the issue...
  depends_on = [
    fivetran_connector.this,
    fivetran_connector_schedule.this
  ]
}
```

**Expected behavior**
I would expect all resources to be created and configured automatically without any manual interventions and without errors.

**Logs & Output**
```
╷
│ Error: create
│
│   with module.fivetran_azure["T0000"].fivetran_connector_schema_config.this,
│   on ../modules/fivetran/connector.tf line 37, in resource "fivetran_connector_schema_config" "this":
│   37: resource "fivetran_connector_schema_config" "this" {
│
│ status code: 400; expected: 200; code: InvalidInput; message: We expected the connector's setup state ('status.setup_state') to be 'connected', but it was 'incomplete'.
│ Please configure the connector and perform the connector setup tests.
╵
╷
│ Error: create
│
│   with module.fivetran_azure["T0001"].fivetran_connector_schema_config.this,
│   on ../modules/fivetran/connector.tf line 37, in resource "fivetran_connector_schema_config" "this":
│   37: resource "fivetran_connector_schema_config" "this" {
│
│ status code: 400; expected: 200; code: InvalidInput; message: We expected the connector's setup state ('status.setup_state') to be 'connected', but it was 'incomplete'.
│ Please configure the connector and perform the connector setup tests.
╵
```
**Plugin version:**
I am using provider v. 0.7.3

**Comment by beevital** [comment] 2023-08-08 14:58
> In the GUI connector has status INCOMPLETE and has to be manually fixed by clicking "Save & test".

Looks like tests weren't run with request from Terraform. Investigating this.
Probably the bug will be fixed in the next release. We already had an issue about setup tests not triggered on connector creation. But the fix wasn't released yet

**Comment by beevital** [comment] 2023-08-08 15:25
@puchtawxebia Could you please clarify service type you were trying to create? (`service            = var.connector.service`)
We have an opened incident with SQL Server HVA connector: setup tests fails for connector created using API. It's not resolved yet.

**Comment by puchtawxebia** [comment] 2023-08-10 10:20
@beevital, sorry I have missed that info. The service is "azure_sql_db".

**Comment by beevital** [comment] 2023-08-10 11:12
Thank you!
Yes - most likely it is related to our issue with setup tests via API, we are working on that!

Also I'm currently working on improvement for our connector resource to make it possible to handle failed setup tests and track actual connector status.

**Comment by kovalsky-tmz** [comment] 2023-10-23 07:44
hello @beevital any news on that topic?

**Comment by beevital** [comment] 2023-11-17 15:06
Hey @kovalsky-tmz issue should be already fixed.
Are you still have the same experience?

**Comment by kovalsky-tmz** [comment] 2023-11-20 16:27
@beevital unfortunatelly yes, Ive updated fivetran provider to latest but still experiencing this issue. I need to manually click "Save and Test" in fivetran connector setup because status is 'incompleted'. After that I also need to choose Microsoft Azure Certificate in popup on "Validating certificate" step. Any ideas how to make it work? 
![image](https://github.com/fivetran/terraform-provider-fivetran/assets/12074285/dee6b0bb-5454-4710-860a-350f5156d8de)

**Comment by beevital** [comment] 2023-11-27 16:51
@kovalsky-tmz I've passed your experience to connector maintainers team. The issue is specific for cloud SQL server.
So we are working on it.

**Comment by beevital** [comment] 2023-12-27 13:11
The issue was resolved on API side, so it should work fine via Terraform.
@kovalsky-tmz please feel free to re-open issue in case of facing the same experience.

**Closed by beevital** 2023-12-27 13:11 UTC
Labels: bug
