### ISSUE TITLE
first time creating a destination - status code: 400; expected: 201; code: InvalidInput; message: Invalid 'config' object

### ISSUE THREAD

**Issue by ann8ty** [fivetran/terraform-provider-fivetran#178] opened 2023-07-28 23:13 UTC
**Describe the bug**
The first time terraform plan/apply runs to create a destination that has not already existed, I get this error.

Rerun, it is fixed.  Switch to next environment / destination and it repeats.  I have seen it 4 times, 100% of the new environments since 0.7.3.  This did not occur on 0.7.2-pre.

**To Reproduce**
```
resource "fivetran_destination" "destination_redshift" {
  group_id           = fivetran_group.group_for_everything.id
  service            = "redshift"
  time_zone_offset   = "0"           
  region             = "GCP_US_EAST4" 
  trust_certificates = "true"
  trust_fingerprints = "true"
  run_setup_tests    = "true"

  config {
    tunnel_host     = data.aws_cloudformation_export.bastion_elastic_ip_export.value
    tunnel_port     = 22
    tunnel_user     = "fivetran"
    host            = local.redshift_host
    port            = 5439
    auth_type       = "PASSWORD"
    user            = jsondecode(data.aws_secretsmanager_secret_version.fivetran_database_user_secret.secret_string)["username"]
    password        = jsondecode(data.aws_secretsmanager_secret_version.fivetran_database_user_secret.secret_string)["password"]
    database        = var.redshift_database
    connection_type = "SSHTunnel"
    cluster_region  = "us-east-2"
  }
}

```

**Expected behavior**

I do not expect an error on first time creation of a destination that is fixed on rerun.

**Logs & Output**
Provide terraform CLI output on `plan` | `apply`. If it is possible, please, refer to [this guide](https://developer.hashicorp.com/terraform/internals/debugging) to enable debug output.

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_secretsmanager_secret.fivetran_public_key_secret will be created
  + resource "aws_secretsmanager_secret" "fivetran_public_key_secret" {
      + arn                            = (known after apply)
      + description                    = "dp2-datainfra-v2 public key for fivetran ssh bastion"
      + force_overwrite_replica_secret = false
      + id                             = (known after apply)
      + name                           = "dp2-datainfra-v2-fivetran-production-schema-v2"
      + name_prefix                    = (known after apply)
      + policy                         = (known after apply)
      + recovery_window_in_days        = 30
      + tags                           = {
          + "Component"    = "tf-fivetran-group"
  # fivetran_destination.destination_redshift_datainfra_v2 will be created
  + resource "fivetran_destination" "destination_redshift_datainfra_v2" {
      + group_id           = (known after apply)
      + id                 = (known after apply)
      + last_updated       = (known after apply)
      + region             = "GCP_US_EAST4"
      + run_setup_tests    = true
      + service            = "redshift"
      + setup_status       = (known after apply)
      + time_zone_offset   = "0"
      + trust_certificates = true
      + trust_fingerprints = true

      + config {
          + auth_type                = "PASSWORD"
          + cluster_region           = "us-east-2"
          + connection_type          = "SSHTunnel"
          + database                 = "removed"
          + host                     = "removed"
          + is_private_key_encrypted = (known after apply)
          + password                 = (sensitive value)
          + port                     = 5439
          + public_key               = (known after apply)
          + tunnel_host              = "removed"
          + tunnel_port              = "22"
          + tunnel_user              = "fivetran"
          + user                     = (sensitive value)
        }
    }

  # fivetran_group.group_for_everything will be created
  + resource "fivetran_group" "group_for_everything" {
      + created_at   = (known after apply)
      + id           = (known after apply)
      + last_updated = (known after apply)
      + name         = "dp2_datainfra_v2_redshift_schema_v2"
    }

Plan: 6 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────

Saved the plan to: production.out

To perform exactly these actions, run the following command to apply:
    terraform apply "production.out"
/home/runner/work/_temp/38e39b9c-73a6-4e37-ac5c-fcfd4b5ab01a/terraform-bin apply production.out
fivetran_group.group_for_everything: Creating...
fivetran_group.group_for_everything: Creation complete after 1s [id=approached_finest]
aws_ssm_parameter.ssm_fivetran_group_id_external_id_data_account: Creating...
aws_secretsmanager_secret.fivetran_public_key_secret: Creating...
fivetran_destination.destination_redshift_datainfra_v2: Creating...
aws_secretsmanager_secret.fivetran_public_key_secret: Creation complete after 1s [id=arn:removed]
aws_ssm_parameter.ssm_fivetran_group_id_external_id_app_account: Creating...
aws_ssm_parameter.ssm_fivetran_group_id_external_id_data_account: Creation complete after 1s [id=/dp2-datainfra-v2/schema-v2/fivetranGroupId]
aws_ssm_parameter.ssm_fivetran_group_id_external_id_app_account: Creation complete after 0s [id=/dp2-datainfra-v2/schema-v2/appenvironment/fivetranGroupId]
╷
│ Error: create error
│ 
│   with fivetran_destination.destination_redshift_datainfra_v2,
│   on destination.tf line 6, in resource "fivetran_destination" "destination_redshift_datainfra_v2":
│    6: resource "fivetran_destination" "destination_redshift_datainfra_v2" {
│ 
│ status code: 400; expected: 201; code: InvalidInput; message: Invalid
│ 'config' object
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

**Plugin version:**
Terraform v1.5.2
on darwin_arm64
+ provider registry.terraform.io/fivetran/fivetran v0.7.3
+ provider registry.terraform.io/hashicorp/aws v5.8.0

**Additional context**
Only on first time, rerun and it works.

**Comment by beevital** [comment] 2023-07-31 11:03
Hi @ann8ty !
I've inspected our API requests log and figured out that terraform client made 100% identical requests, but API returned 400 on the first one.
It looks like we have bug on API side, not related to terraform. 
I've created an internal ticket for API team.

Will return to you here after investigation.

**Comment by beevital** [comment] 2023-07-31 11:15
BTW: 
```
connection_type          = "SSHTunnel"
```
Is incorrect, here is an error form API logs:
```
"cause" : {
      "className" : "com.fasterxml.jackson.databind.exc.InvalidFormatException",
      "message" : "Cannot deserialize value of type `com.fivetran.core.ConnectionType` from String "SSHTunnel": not one of the values accepted for Enum class: [SshTunnel, PrivateLink, Directly, ProxyAgent]"
```

But I'm wondering how it worked on second attemt.
It's definitely BUG on API side, and it should return 400 to you in both cases.

Please use:
```
connection_type = "SshTunnel"
```

**Comment by beevital** [comment] 2023-08-22 15:37
We were not able to reproduce described behavior on API side. 
Terraform provider works correctly and logged request payload mapped perfectly from terraform configuration.

I have to close this issue.

**Closed by beevital** 2023-08-22 15:37 UTC
Labels: bug
